blank_issues_enabled: false
contact_links:
  - name: Transaction Form 1
    url: https://treasuryguild.github.io/treasury-v3/
    about: Fill in this form when you make a transaction (Complete form 1 and 2)
  - name: Transaction Form 2
    url: https://github.com/treasuryguild/Lead-Generators/issues/new
    about: Fill in this form after you made a transaction (Complete form 1 and 2)
